# Generated by Django 2.0.2 on 2018-04-28 04:17

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(null=True, upload_to=uuid_upload_path.storage.upload_to)),
                ('linked_in', models.CharField(blank=True, max_length=200, null=True)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('stack_overflow', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
